version: "3.7"

volumes:
  d-bus-volume:

services:
  d-bus-service:
    build:
      context: d-bus-service
    image: jbaptperez/wirepas-d-bus-service:latest
    restart: always
    volumes:
      - type: volume
        source: d-bus-volume
        target: /var/run/dbus

  sink-service-0:
    build:
      context: sink-service
    image: jbaptperez/wirepas-sink-service:latest
    restart: always
    depends_on:
      - d-bus-service
    environment:
      WM_GW_SINK_ID: "0"
      WM_GW_SINK_UART_PORT: "/dev/serial/by-wirepas-sink-id/0"
      WM_GW_SINK_BITRATE: "125000"
    volumes:
      - type: volume
        source: d-bus-volume
        target: /var/run/dbus
    devices:
      - "${SINK_0_PATH:-/dev/serial/by-wirepas-sink-id/0}:/dev/serial/by-wirepas-sink-id/0"

  sink-service-1:
    build:
      context: sink-service
    image: jbaptperez/wirepas-sink-service:latest
    restart: always
    depends_on:
      - d-bus-service
    environment:
      WM_GW_SINK_ID: "1"
      WM_GW_SINK_UART_PORT: "/dev/serial/by-wirepas-sink-id/1"
      WM_GW_SINK_BITRATE: "125000"
    volumes:
      - type: volume
        source: d-bus-volume
        target: /var/run/dbus
    devices:
      - "${SINK_1_PATH:-/dev/serial/by-wirepas-sink-id/1}:/dev/serial/by-wirepas-sink-id/1"

  sink-service-2:
    build:
      context: sink-service
    image: jbaptperez/wirepas-sink-service:latest
    restart: always
    depends_on:
      - d-bus-service
    environment:
      WM_GW_SINK_ID: "2"
      WM_GW_SINK_UART_PORT: "/dev/serial/by-wirepas-sink-id/2"
      WM_GW_SINK_BITRATE: "125000"
    volumes:
      - type: volume
        source: d-bus-volume
        target: /var/run/dbus
    devices:
      - "${SINK_2_PATH:-/dev/serial/by-wirepas-sink-id/2}:/dev/serial/by-wirepas-sink-id/2"

  sink-service-3:
    build:
      context: sink-service
    image: jbaptperez/wirepas-sink-service:latest
    restart: always
    depends_on:
      - d-bus-service
    environment:
      WM_GW_SINK_ID: "3"
      WM_GW_SINK_UART_PORT: "/dev/serial/by-wirepas-sink-id/3"
      WM_GW_SINK_BITRATE: "125000"
    volumes:
      - type: volume
        source: d-bus-volume
        target: /var/run/dbus
    devices:
      - "${SINK_3_PATH:-/dev/serial/by-wirepas-sink-id/3}:/dev/serial/by-wirepas-sink-id/3"

  transport-service:
    build:
      context: transport-service
    image: jbaptperez/wirepas-transport-service:latest
    restart: always
    depends_on:
      - d-bus-service
      - mosquitto-service
    environment:
      WM_GW_MODEL: "lxgw"
      WM_GW_VERSION: "gitbuild"
      WM_GW_IGNORED_ENDPOINTS_FILTER: ""
      WM_GW_WHITENED_ENDPOINTS_FILTER: ""
      WM_SERVICES_MQTT_HOSTNAME: "mosquitto-service"
      WM_SERVICES_MQTT_PORT: "1883"
      WM_SERVICES_MQTT_USERNAME: "${WM_SERVICES_MQTT_USERNAME:-mqttuser}"
      WM_SERVICES_MQTT_PASSWORD: "${WM_SERVICES_MQTT_PASSWORD:-mqttpassword}"
      WM_SERVICES_MQTT_CA_CERTS: "/etc/my-tls-file"
      WM_SERVICES_MQTT_ALLOW_UNTRUSTED: "true"
      WM_SERVICES_MQTT_FORCE_UNSECURE: "true"
      PYTHONUNBUFFERED: "true"
    volumes:
      - type: volume
        source: d-bus-volume
        target: /var/run/dbus

  mosquitto-service:
    build:
      context: mosquitto-service
    image: jbaptperez/wirepas-mosquitto-service:latest
    restart: always
    environment:
      WM_SERVICES_MQTT_USERNAME: "${WM_SERVICES_MQTT_USERNAME:-mqttuser}"
      WM_SERVICES_MQTT_PASSWORD: "${WM_SERVICES_MQTT_PASSWORD:-mqttpassword}"
    ports:
      - published: ${WM_SERVICES_MQTT_PORT:-1883}
        target: 1883
        protocol: tcp
        mode: host
